parameters:
    cart.session_key: '%env(CART_SESSION_KEY)%'
    login_route: '%env(LOGIN_ROUTE)%'
    homepage: '%env(HOMEPAGE)%'
    admin_panel: '%env(ADMIN_PANEL)%'
    github_client_id: '%env(GITHUB_CLIENT_ID)%'
    github_client_secret: '%env(GITHUB_CLIENT_SECRET)%'
    google_client_id: '%env(GOOGLE_CLIENT_ID)%'
    google_client_secret: '%env(GOOGLE_CLIENT_SECRET)%'
    upload_directory: '%kernel.project_dir%/public/uploads/products'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\Cart\Factory\Guest\GuestCartFactory:
        arguments:
            $cartSessionKey: '%cart.session_key%'

    App\Security\LoginFormAuthenticator:
        arguments:
            $loginRoute: '%login_route%'
            $homepage: '%homepage%'
            $adminPanel: '%admin_panel%'

    Redis:
        class: Redis
        calls:
            - method: connect
              arguments:
                  - '%env(REDIS_HOST)%'
                  - '%env(int:REDIS_PORT)%'

    App\Command\UpdateViewsCommand:
        arguments:
            $keyPrefix: '%env(REDIS_PRODUCT_VIEWS_KEY_PREFIX)%'

    App\Service\Product\Views\ProductViewsService:
        arguments:
            $keyPrefix: '%env(REDIS_PRODUCT_VIEWS_KEY_PREFIX)%'

    App\Service\OAuth\Provider\GitHub\GitHubOAuthProvider:
        arguments:
            $clientId: '%github_client_id%'
            $clientSecret: '%github_client_secret%'

    App\Service\OAuth\Provider\Google\GoogleOAuthProvider:
        arguments:
            $clientId: '%google_client_id%'
            $clientSecret: '%google_client_secret%'

    App\Twig\MoneyExtension:
        tags: [ 'twig.extension' ]

    s3_client:
        class: Aws\S3\S3Client
        arguments:
            - version: 'latest'
              region: '%env(AWS_REGION)%'
              endpoint: '%env(AWS_ENDPOINT)%'
              use_path_style_endpoint: true
              credentials:
                  key: '%env(AWS_ACCESS_KEY_ID)%'
                  secret: '%env(AWS_SECRET_ACCESS_KEY)%'

    App\Service\Storage\Manager\StorageManager:
        arguments:
            $awsEndpoint: '%env(AWS_ENDPOINT)%'
            $awsBucket: '%env(AWS_BUCKET)%'
            $directory: 'upload_directory%'

    App\Service\Storage\Factory\StorageFactory:
        arguments:
            $localStorage: '@local.storage'
            $s3Storage: '@s3.storage'
            $storageType: '%env(STORAGE_ADAPTER)%'
